### ISSUE TITLE
Connect hours table to endpoint

### ISSUE THREAD

**Issue by mihikaiyer** [Code-4-Community/breaktime-frontend#2]
Call GET api/v1/protected/hours/:userID and show data in existing table
Create filter to select start date and end date for viewing previous hours
https://www.figma.com/file/P2DZZXSjkBe5wwakk78iPA/Pay-log?node-id=99%3A69&t=6CBsLdCWYGqhhZCL-1

Returned data will be of the following format: 
`'12/06-12/10':{`
         `'editable':false,`
          `'companyId':'XXXXXX',`
        `'state':'Completed / In-Review (Employer or Breaktime) / Unsubmitted / Rejected',`
        `'report_type':{'Type':'Comment', 'Message':'', 'UUID':'XXXX','Timestamp':''},`
        `'hours':`
`[{'uuid':'XXXXXXX','startDate':"February 14 2023 9:00:00 GMT-0500", 'endDate':"February 14 2023 15:00:00 GMT-0500", 'report_type':{'Type':'Comment / Report', 'Message':'', 'UUID':'XXXX','Timestamp':''}}]}`

Terms of Acceptance
* Update appropriate callbacks / useEffects to properly load this data as default

**Comment by kennedyry** [comment]
@mihikaiyer updated this to include what we talked about it work meeting this weekend for what should be included in response
